name: DefenseCode ThunderScan Action

on:
  push:
    branches: [ master develop feature/optimize_intelligent_mode ]
  pull_request:
    branches: [ master develop ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: defensecode/thunderscan-action@v1.0
    - name: make
      run: make -f makefile.unx
    - name: test
      run: bash scripts/solveExamples.sh
